### PR TITLE
Project Testing with Ruby - Tic Tac Toe

### PR DESCRIPTION
**Pull request by mgunduz1**
Tests for Tic-Tac-Toe project. Built with Ruby, Rubocop and Rspec.

Added tests for all content.
All tests are returning correct.
Made with project requirements.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @mgunduz1 and @Bishoy-Samwel 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Add testing Setup in the README file
- [x] Remove `require 'terminal-table'` from `table.rb`
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
-----------------
Hello @Bishoy-Samwel @mgunduz1 :wave: you are doing an excellent job on this project :clap: :muscle: 
However, there are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
--------------

- [x] Improve your commit messages. Remember that the commit messages must be imperative. [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can read the formatting rules. [Here ](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) you can read how to changes a commit message. You don't need to changes the commit messages this time but keep that formating rule for the next commit messages. 
- [x] Don't changes the original rubocop file. Please use the original one. 

linter_config

- [x] Add a negative scenario for your RSpec. The RSpec is for testing if your app is working properly it means that should test negative scenarios too. E.g `It does not return true if the condition is not met().not_to eql(true)` 
- [x] Write a better message for the RSpec. These messages are to know what is the scenario you are testing. `condition1` is not telling me what is the condition. Please write a meaningful message. 
-------------
Make these required changes and send it for another review. :hammer_and_wrench: :smile: 
HAPPY CODING!!1

**Comment by mgunduz1** [comment]
> ## CHANGES REQUIRED  
> ## Hello @Bishoy-Samwel @mgunduz1  you are doing an excellent job on this project  
> However, there are a few changes to make to complete this project  see them below  
> * [x]  Improve your commit messages. Remember that the commit messages must be imperative. [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can read the formatting rules. [Here ](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) you can read how to changes a commit message. You don't need to changes the commit messages this time but keep that formating rule for the next commit messages.
> * [x]  Don't changes the original rubocop file. Please use the original one.
> 
> linter_config
> 
> * [x]  Add a negative scenario for your RSpec. The RSpec is for testing if your app is working properly it means that should test negative scenarios too. E.g `It does not return true if the condition is not met().not_to eql(true)`
> * [x]  Write a better message for the RSpec. These messages are to know what is the scenario you are testing. `condition1` is not telling me what is the condition. Please write a meaningful message.
> 
> Make these required changes and send it for another review.  
> HAPPY CODING!!1
> 
> 

1.  Rubocop usage is the same with the original that got approved after 4 different pull requests. There was really a mild usage of disable rubocop.
2. Only thing that changes about linter is max metric length 30 to 45. A lot of people did minor changes on this milestone you can check other projects.
3. Last thing, i really like how every single tse in microverse has different standards. It's really not confusing at all.

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] All tests ar passing 💯

- ### To Improve
  - N/A.

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
